<?php
//sessions validation between pages
//Starting the session
session_start();
//session_id() returns the actual session ID created by the server
$SID = session_id();
//display text to webpage
echo 'Sessions Page Two<br />';
//display user variable
echo 'User Variable: '.$_SESSION['user'];
//display the session ID that was generated by the session _start() command 
echo '<br /> Session id: '.$SID;
echo ' <BR /><BR /><BR />';
//create and display a link for the previous page 
echo '<a href="sessions1.php">Sessions Page One</a> ';
echo ' <BR /><BR /><BR />';
//create and display a link for the next page 
echo '<a href="sessions3.php">Sessions Logout Page</a> ';
?>